---
hdp_minor_version: "{{ hdp_version | regex_replace('.[0-9]+.[0-9]+[0-9_-]*$','') }}"
hdp_major_version: "{{ hdp_minor_version.split('.').0 }}"
hdf_minor_version: "{{ hdf_version | regex_replace('.[0-9]+.[0-9]+[0-9_-]*$','') }}"
hdf_major_version: "{{ hdf_minor_version.split('.').0 }}"

hdp_main_repo_url: "{{ base_url }}/HDP/centos6/{{ hdp_major_version }}.x/updates/{{ hdp_version }}"
hdf_main_repo_url: "{{ base_url }}/HDF/centos6/{{ hdf_major_version }}.x/updates/{{ hdf_version }}"
main_os_target: "operating_systems/redhat6"

utils_repo_url: "{{ base_url }}/HDP-UTILS-{{ utils_version }}/repos/centos6"
utils_os_target: "operating_systems/redhat6/repositories/HDP-UTILS-{{ utils_version }}"
