---
hdp_minor_version: "{{ hdp_version | regex_replace('.[0-9]+.[0-9]+[0-9_-]*$','') }}"
hdp_major_version: "{{ hdp_minor_version.split('.').0 }}"
hdf_minor_version: "{{ hdf_version | regex_replace('.[0-9]+.[0-9]+[0-9_-]*$','') }}"
hdf_major_version: "{{ hdf_minor_version.split('.').0 }}"

hdp_main_repo_url: "{{ base_url }}/HDP/sles12/{{ hdp_major_version }}.x/updates/{{ hdp_version }}"
hdf_main_repo_url: "{{ base_url }}/HDF/sles12/{{ hdf_major_version }}.x/updates/{{ hdf_version }}"
main_os_target: "operating_systems/suse{{ ansible_distribution_major_version }}"

utils_repo_url: "{{ base_url }}/HDP-UTILS-{{ utils_version }}/repos/sles12"
utils_os_target: "operating_systems/suse{{ ansible_distribution_major_version }}/repositories/HDP-UTILS-{{ utils_version }}"
