---
postgres_packages:
  - postgresql-server
postgres_service_name: postgresql
postgres_initdb_command: service postgresql initdb
postgres_unix_socket: /var/run/postgresql
postgres_config_file: /var/lib/pgsql9/data/postgresql.conf
postgres_hba_file: /var/lib/pgsql9/data/pg_hba.conf

mysql_repo_url: 'http://repo.mysql.com/yum/mysql-5.6-community/el/6/$basearch/'
mysql_repo_key: 'http://repo.mysql.com/RPM-GPG-KEY-mysql'
mysql_packages:
  - mysql56-server
  - MySQL-python27
mysql_service_name: mysqld

mariadb_repo_url: 'http://yum.mariadb.org/10.1/centos6-amd64'
mariadb_repo_key: 'http://yum.mariadb.org/RPM-GPG-KEY-MariaDB'
mariadb_packages:
  - MariaDB-server
  - MySQL-python27
mariadb_service_name: mysql
