---
postgres_packages:
  - postgresql-server
postgres_service_name: postgresql
postgres_initdb_command: postgresql-setup initdb
postgres_unix_socket: /var/run/postgresql
postgres_config_file: /var/lib/pgsql/data/postgresql.conf
postgres_hba_file: /var/lib/pgsql/data/pg_hba.conf

mysql_repo_url: 'http://repo.mysql.com/yum/mysql-5.6-community/el/7/$basearch/'
mysql_repo_key: 'http://repo.mysql.com/RPM-GPG-KEY-mysql'
mysql_packages:
  - mysql-community-server
  - MySQL-python
mysql_service_name: mysql

mariadb_repo_url: 'http://yum.mariadb.org/10.1/centos7-amd64'
mariadb_repo_key: 'http://yum.mariadb.org/RPM-GPG-KEY-MariaDB'
mariadb_packages:
  - MariaDB-server
  - MySQL-python
mariadb_service_name: mariadb
