---
postgres_packages:
  - postgresql94
  - postgresql-jdbc
postgres_jdbc_location: /usr/share/java/postgresql-jdbc.jar

mysql_packages:
  - python-mysql
  - mysql-connector-java
mysql_jdbc_location: /usr/share/java/mysql-connector-java.jar
