---
ambari_repo_url: "http://public-repo-1.hortonworks.com/ambari/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}/2.x/updates/{{ ambari_version }}/ambari.list"
ambari_repo_destination: "/etc/apt/sources.list.d/ambari.list"
ambari_repo_key: "B9733A7A07513CAD"
ambari_repo_keyserver: "keyserver.ubuntu.com"
